# Generated by Django 3.2.6 on 2021-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('g_id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=254)),
                ('g_contact', models.CharField(max_length=254)),
                ('g_email', models.EmailField(max_length=254)),
                ('g_fare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('s_id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=254)),
                ('s_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WildLife',
            fields=[
                ('w_id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=254)),
                ('w_type', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
