# Generated by Django 3.2.6 on 2021-09-21 18:07

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sundarbans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('Primary', 'Primary'), ('Standard', 'Standard'), ('Combo', 'Combo')], max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='g_fare',
        ),
        migrations.AddField(
            model_name='guide',
            name='g_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='s_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='wildlife',
            name='w_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spot',
            name='s_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
